=== bryanvanhuyneghem/Data-Technologies/1_DTD_XMLSchema/imdb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
<xsd:element name="imdb">
   <xsd:complexType>
      <xsd:sequence>
	   <xsd:element ref="films"/>
	   <xsd:element ref="personen"/>
	   <xsd:element ref="filmmaatschappijen"/>
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>
	
<xsd:element name="films">
   <xsd:complexType>
      <xsd:choice maxOccurs="unbounded" minOccurs="0">
           <xsd:element name="animatiefilm" type="animatiefilmtype" 
                        minOccurs="1" maxOccurs="1"/>
           <xsd:element name="film" type="filmtype" 
                        maxOccurs="1" minOccurs="1"/>
      </xsd:choice>
   </xsd:complexType>
</xsd:element>
	

<xsd:complexType name="animatiefilmtype">
   <xsd:sequence>
	<xsd:element name="titel" type="xsd:string"/>
	<xsd:element ref="cast"/>
	<xsd:element name="regisseur" minOccurs="1" maxOccurs="unbounded">
           <xsd:complexType>
              <xsd:attribute name="naam" use="required" type="xsd:IDREF"/>
	   </xsd:complexType>
	</xsd:element>
	<xsd:element name="speelduur" type="xsd:nonNegativeInteger"/>
	<xsd:element name="maatschappijen">
	   <xsd:complexType>
		<xsd:sequence>
	 	   <xsd:element name="maatschappij" 
                                minOccurs="1" maxOccurs="unbounded">
			<xsd:complexType>
		 	    <xsd:attribute name="naam" use="required" 
                                           type="xsd:IDREF"/>
			</xsd:complexType>
		   </xsd:element>
		</xsd:sequence>
	   </xsd:complexType>
	</xsd:element>
   </xsd:sequence>
   <xsd:attribute name="id" use="required" type="xsd:ID"/>
   <xsd:attribute name="beoordeling" use="required" type="beoordelingType"/>
</xsd:complexType>
        

<xsd:simpleType name="beoordelingType">
   <xsd:restriction base="xsd:string">
	<xsd:pattern value="(KT|KNT)"/>
   </xsd:restriction>
</xsd:simpleType>
        
<xsd:complexType name="filmtype">
   <xsd:complexContent>
	<xsd:extension base="animatiefilmtype">
	   <xsd:sequence>
 	      <xsd:element name="filmlocatie" type="xsd:string"/>
	   </xsd:sequence>
	</xsd:extension>
   </xsd:complexContent>
</xsd:complexType>

<xsd:element name="personen">
   <xsd:complexType>
	<xsd:sequence>
 	   <xsd:element ref="persoon" maxOccurs="unbounded"/>
	</xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="persoon">
   <xsd:complexType>
	<xsd:sequence>
 	   <xsd:element name="naam" minOccurs="1" maxOccurs="1" 
                        type="xsd:string"/>
	   <xsd:element name="geboortedatum" minOccurs="1" maxOccurs="1" 
                        type="datumType"/>
	   <xsd:element name="geboorteplaats" minOccurs="1" maxOccurs="1" 
                        type="xsd:string"/>
	   <xsd:element name="geslacht" minOccurs="1" maxOccurs="1" 
                        type="geslachtType"/>
	   <xsd:element name="foto" minOccurs="1" maxOccurs="1" 
                        type="fotoType"/>
	</xsd:sequence>
	<xsd:attribute name="id" use="required" type="xsd:ID"/>
   </xsd:complexType>
</xsd:element>

<xsd:simpleType name="fotoType">
   <xsd:restriction base="xsd:string">
	<xsd:pattern value="[a-zA-Z0-9]*\.jpg"/>
   </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="datumType">
   <xsd:restriction base="xsd:string">
	<xsd:pattern value="[0-3][0-9]/[0-1][0-9]/[12][0-9]{3}"/>
   </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="geslachtType">
   <xsd:restriction base="xsd:string">
	<xsd:pattern value="[mvMV]"/>
   </xsd:restriction>
</xsd:simpleType>
        
<xsd:element name="filmmaatschappijen">
   <xsd:complexType>
	<xsd:sequence>
	   <xsd:element ref="filmmaatschappij" maxOccurs="unbounded"/>
	</xsd:sequence>
   </xsd:complexType>
</xsd:element>        

<xsd:element name="filmmaatschappij">
   <xsd:complexType>
	<xsd:sequence>
	   <xsd:element name="naam" minOccurs="1" maxOccurs="1" 
                        type="xsd:string"/>
	   <xsd:element name="website" minOccurs="0" maxOccurs="1" 
                        type="xsd:string"/>
	</xsd:sequence>
	<xsd:attribute name="id" use="required" type="xsd:ID"/>
   </xsd:complexType>
</xsd:element>
	
<xsd:element name="cast">
   <xsd:complexType>
      <xsd:sequence>
         <xsd:element name="personage" maxOccurs="unbounded">
	    <xsd:complexType>
	        <xsd:simpleContent>
		   <xsd:extension base="xsd:string">
		      <xsd:attribute name="acteur" type="xsd:IDREF" 
                                     use="required"/>
		   </xsd:extension>
		</xsd:simpleContent>
	    </xsd:complexType>
	 </xsd:element>
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>
        
</xsd:schema>

=== bryanvanhuyneghem/Data-Technologies/1_DTD_XMLSchema/imdb_fout.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE imdb SYSTEM "imdb.dtd">
<imdb>
<!--<imdb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="imdb.xsd">-->
    <films>
        <film id="MPATHG" beoordeling="KT">
            <titel>Monty Python and the Holy Grail</titel>
            <cast>
                <personage acteur="GCHAPMAN">
                    King Arthur
                </personage>
                <personage acteur="GCHAPMAN">
                    Voice of God
                </personage>
                <personage acteur="GCHAPMAN">
                    Middle Head
                </personage>
                <personage acteur="GCHAPMAN">
                    Hiccoughing Guard
                </personage>
                <personage acteur="JCLEESE">
                    The Black Knight
                </personage>
                <personage acteur="JCLEESE">
                    Sir Lancelot, the Brave
                </personage>
                <personage acteur="JCLEESE">
                    Taunting French Guard
                </personage>
                <personage acteur="JCLEESE">
                    Tim the Enchanter
                </personage>
                <personage acteur="EIDLE">
                    Sir Robin the Not-Quite-So-Brave-as-Sir Launcelot
                </personage>
                <personage acteur="EIDLE">
                    Dead Collector
                </personage>
                <personage acteur="EIDLE">
                    Roger the Shrubber
                </personage>
            </cast>
            <regisseur naam="TJONES"/>
            <speelduur>91</speelduur>
            <maatschappijen>
                <maatschappij naam="MICHAELWHITE"/>
            </maatschappijen>
            <filmlocatie>
                Appin, Argyll, Scotland, UK
            </filmlocatie>
        </film>
        <animatiefilm id="TI" beoordeling="KT">
            <titel>The Incredibles</titel>
            <cast>
                <personage acteur="CNELSON">
                    Bob Parr
                </personage>
                <personage acteur="CNELSON">
                    Mr. Incredible
                </personage>
                <personage acteur="HHUNTER">
                    Helen Parr
                </personage>
                <personage acteur="HHUNTER">
                    Helen Parr
                </personage>
                <personage acteur="SJACKSON">
                    Lucius Best
                </personage>
                <personage acteur="SJACKSON">
                    Frozone
                </personage>
                <personage acteur="JLEE">
                    Buddy Pine
                </personage>
                <personage acteur="JLEE">
                    Syndrome
                </personage>
            </cast>
            <regisseur naam="BBIRD"/>
            <speelduur>115</speelduur>
            <maatschappijen>
                <maatschappij naam="WALTDISNEYPICTURES"/>
            </maatschappijen>
        </animatiefilm>
        <animatiefilm id="IA" beoordeling="KT">
            <titel>Ice Age</titel>
            <cast>
                <personage acteur="RROMANO">
                    Manfred
                </personage>
                <personage acteur="JLEGUIZAMO">
                    Sid
                </personage>
                <personage acteur="DLEARY">
                    Diego
                </personage>
            </cast>
            <regisseur naam="CWEDGE"/>
            <regisseur naam="CSALDANHA"/>
            <speelduur>81</speelduur>
            <maatschappijen>
                <maatschappij naam="BLUESKYSTUDIO"/>
            </maatschappijen>
        </animatiefilm>
        <film id="TSR" beoordeling="KNT">
            <titel>The Shawshank Redemption</titel>
            <cast>
                <personage acteur="TROBBINS">
                    Andy Dufresne
                </personage>
                <personage acteur="MFREEMAN">
                    Ellis Boyd 'Red' Redding
                </personage>
                <personage acteur="BGUNTON">
                    Warden Norton
                </personage>
                <personage acteur="WSADLER">
                    Heywood
                </personage>
                <personage acteur="CBROWN">
                    Captain Hadley
                </personage>
            </cast>
            <regisseur naam="FDARABONT"/>
            <speelduur>-142</speelduur>
            <maatschappijen>
                <maatschappij naam="CASTLEROCK"/>
            </maatschappijen>
            <filmlocatie>
                Ashland, Ohio, USA 
            </filmlocatie>
        </film>
        <film id="TDK" beoordeling="KT">
            <titel>The Dark Knight</titel>
            <cast>
                <personage acteur="CBALE">
                    Bruce Wayne
                </personage>
                <personage acteur="CBALE">
                    Batman
                </personage>
                <personage acteur="MFREEMAN">
                    Lucius Fox
                </personage>
                <personage acteur="MCAINE">
                    Alfred
                </personage>
                <personage acteur="HLEDGER">
                    The Joker
                </personage>
                <personage acteur="MGYLLENHAAL">
                    Rachel Dawes
                </personage>
            </cast>
            <regisseur naam="CNOLAN"/>
            <speelduur>152</speelduur>
            <maatschappijen>
                <maatschappij naam="WARNERBROS" />
                <maatschappij naam="LEGENDARYPICTURES" />
            </maatschappijen>
            <filmlocatie>
                Atwood Cafe - 1 W Washington St, Chicago, Illinois, USA
            </filmlocatie>
        </film>
        <film id="PF" beoordeling="KNT">
            <titel>Pulp Fiction</titel>
            <cast>
                <personage acteur="JTRAVOLTA">
                    Vincent Vega
                </personage>
                <personage acteur="SJACKSON">
                    Jules Winnifield
                </personage>
                <personage acteur="BWILLIS">
                    Butch Coolidge
                </personage>
                <personage acteur="UTHURMAN">
                    Mia Wallace
                </personage>
            </cast>
            <regisseur naam="QTARANTINO"/>
            <speelduur>154</speelduur>
            <maatschappijen>
                <maatschappij naam="MIRAMAX" />
            </maatschappijen>
            <filmlocatie>
                Hawthorne Grill - 13763 S. Hawthorne Boulevard, Hawthorne, California, USA
            </filmlocatie>
        </film>
        <film id="NCFOM" beoordeling="KNT">
            <titel>No Country for old men.</titel>
            <cast>
                <personage acteur="TLJONES">
                    Sherriff Ed Tom Bell
                </personage>
                <personage acteur="JBARDEM">
                    Anton Chigurh
                </personage>
                <personage acteur="WHARRELSON">
                    Carson Wells
                </personage>
                <personage acteur="JBROLIN">
                    Llewelyn Moss
                </personage>
                <personage acteur="KMACDONALD">
                    Carla Jean Moss
                </personage>
            </cast>
            <regisseur naam="ECOEN"/>
            <regisseur naam="JCOEN"/>
            <speelduur>122</speelduur>
            <maatschappijen>
                <maatschappij naam="PARAMOUNTVANTAGE"/>
                <maatschappij naam="MIRAMAX"/>
            </maatschappijen>
            <filmlocatie>
                Albuquerque, New Mexico, USA
            </filmlocatie>
        </film>
        <film id="KBV1" beoordeling="KNT">
            <titel>Kill Bill: Vol 1</titel>
            <cast>
                <personage acteur="UTHURMAN">
                    The Bride
                </personage>
                <personage acteur="LLIU">
                    O-Ren Ishii
                </personage>
                <personage acteur="VFOX">
                    Vernita Green
                </personage>
                <personage acteur="DHANNAH">
                    Elle Driver
                </personage>
            </cast>
            <regisseur naam="QTARANTINO"/>
            <speelduur>111</speelduur>
            <maatschappijen>
                <maatschappij naam="MIRAMAX"/>
            </maatschappijen>
            <filmlocatie>
                Austin, Texas, USA
            </filmlocatie>
        </film>
        <film id="D" beoordeling="KT">
            <titel>Daens</titel>
            <cast>
                <personage acteur="JDECLEIR">
                    Priester Daens
                </personage>
                <personage acteur="GDESARTHE">
                    Charles Woeste
                </personage>
                <personage acteur="ADEBOECK">
                    Nette Scholliers
                </personage>
                <personage acteur="MPAS">
                    Jan De Meeter
                </personage>
            </cast>
            <regisseur naam="SCONINX"/>
            <speelduur>138</speelduur>
            <maatschappijen>
                <maatschappij naam="FAVOURITEFILMS" />
            </maatschappijen>
            <filmlocatie>
                Aalst, Belgium
            </filmlocatie>
        </film>
        <film id="LVEB" beoordeling="KT">
            <titel>La Vita e Bella</titel>
            <cast>
                <personage acteur="RBENIGNI">
                    Guido Orefice
                </personage>
                <personage acteur="NBRASCHI">
                    Dora
                </personage>
            </cast>
            <regisseur naam="RBENIGNI"/>
            <speelduur>116</speelduur>
            <maatschappijen>
